Imgprocess/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from Imgprocess import settings
from images import  views
from django.views.generic import RedirectView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('images.urls'))
    # url(r'^$', RedirectView.as_view(url='/images/home/', permanent=True)),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

images/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

urlpatterns =[
    url(r'^$',views.home,name='home'),
    url(r'^submit/$',views.submit,name='submit'),
]
# # -*- coding: utf-8 -*-
# from django.conf.urls import patterns , url
#
# urlpatterns = patterns(
#     'myproject.myapp.views',
#     url(r'^list/$', 'list', name='list'),
# )

images/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

#
# class Category(models.Model):
#
#     class Meta :
#         verbose_name_plural='categories'
#
#     name=models.CharField(max_length=32)
#
#     def __str__(self):
#         return self.name


class Item(models.Model):
    image=models.ImageField(upload_to='documents/%Y/%m/%d')
    # category=models.ForeignKey(Category)

    # def __str__(self):
    #     return self.name



# Create your models here.

images/forms.py
from django import forms


class ItemForm(forms.Form):
    image = forms.ImageField(
        label='Select a file'
    )

images/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response,render,redirect
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from models import Item
from forms import ItemForm



def home(request):
    # Handle file upload
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Item(image=request.FILES['image'])
            newdoc.save()

            # Redirect to the document list after POST
            return render(request,'images/home.html')
    else:
        form = ItemForm()  # A empty, unbound form

    # Load documents for the list page
    documents = Item.objects.last()
    context_instance = RequestContext(request)

    # Render list page with the documents and the form
    return render(request,
        'images/home.html',
        {'documents': documents, 'form': form},context_instance

    )
def submit(request):
    document = Item(image=request.FILES['image'])
    document.save()
    return redirect('/')

    # template=loader.get_template('images/home.html')
    # contest={
    #     'image':Item.objects.get(id=3)
    # }
    # return HttpResponse(template.render(contest,request))




    # template=loader.get_template('home.html')
    # context={
    # context={
    #     'items':Item.objects.all()
    # }
    # return HttpResponse(template.render(context,request))

# def login(request,item_id):
#     template = loader.get_template('login.html')
#     context = {
#         'item': Item.objects.get(id=item_id )
#     }
#     return HttpResponse(template.render(context,request))

images/templates/images/home.html
<!DOCTYPE html>
<html>
  <head>
    {% load static %}
    <h1 align="center" class="omr">OMR On Openlayers </h1>
    <title>Image Load Events</title>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.4.2/css/ol.css" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <!-- The line below is only needed for old environments like Internet Explorer and Android 4.x -->
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script src="https://openlayers.org/en/v4.4.2/build/ol.js"></script>
  </head>
  <style>
        .omr {

        color:violet;
        }
        .submit{
      color:white;
      background-color:green;
        }
        .image{
          background-color:#d2d8de;
        }
  </style>
  <body>
    <div class="container">
    <div>
    <div >
    <form action="/submit/" method="post" enctype="multipart/form-data">{% csrf_token %}
     <p>
        <input id="id_image" type="file" class="uploading" name="image">
     </p>
      <input type="submit"  class="submit btn btn-md" value="Submit"/>
    </form>
    </div>
    <br>
    <br>
    <div id="image" class="image"></div>
    <script>

      // Map views always need a projection.  Here we just want to map image
      // coordinates directly to map coordinates, so we create a projection that uses
      // the image extent in pixels.
      var extent = [0, 0, 1024, 968];
      var projection = new ol.proj.Projection({
        code: 'xkcd-image',
        units: 'pixels',
        extent: extent

      });

      var map = new ol.Map({
        layers: [
          new ol.layer.Image({
            source: new ol.source.ImageStatic({
              attributions: '© <a href="http://xkcd.com/license.html">xkcd</a>',
              url:'{{ documents.image.url }}',
              projection: projection,
              imageExtent: extent

            })
          })
        ],
        target: 'image',
        view: new ol.View({
          projection: projection,
          center: ol.extent.getCenter(extent),
          zoom: 1.5,
          maxZoom: 8

        })
      });
    </script>
      </div>
  </body>
</html>